FROM ghcr.io/i-on-project/flyway-postgres:latest AS flyway
FROM postgres:alpine

RUN apk add --no-cache docker docker-compose openjdk11-jre-headless

# RUN mkdir -p /var/lib/postgres
# RUN chown postgres:postgres /var/lib/postgres

COPY --from=flyway ./flyway ./
RUN chmod -R a+rx ./flyway

USER postgres

COPY . ./db

ENTRYPOINT [ "./db/bin/start_test_database" ]

EXPOSE 5432

CMD [ "postgres" ]