FROM openjdk:8-jdk-alpine AS builder

WORKDIR /proj
COPY . .
RUN ./gradlew assemble
RUN mv "$(find ./build/libs/*.jar | head -n 1)" ./build/libs/server.jar

FROM openjdk:8-jdk-alpine

RUN addgroup -S spring && adduser -S spring -G spring
EXPOSE 8080/tcp

WORKDIR /home/spring/server
COPY --from=builder /proj/build/libs/server.jar ./
USER spring

ENTRYPOINT ["java", "-server", "-jar", "server.jar", "--spring.profiles.active=default"]
