FROM node:16-alpine3.11 AS node

WORKDIR ./core-react
COPY ./core-react/package.json package.json
COPY ./core-react/yarn.lock yarn.lock

RUN yarn install

COPY ./core-react .
COPY ./jvm ../jvm

RUN yarn build

WORKDIR ..

FROM adoptopenjdk/openjdk11:alpine AS jvm

ARG JDBC_DATABASE_URL
ARG ION_CORE_SECRET_KEY

COPY --from=node ./jvm ./proj
COPY ./.docker ./proj/.docker

WORKDIR /proj
RUN ./gradlew extractUberJar --no-daemon --stacktrace

FROM adoptopenjdk/openjdk11:alpine AS run

RUN addgroup -S spring && adduser -S spring -G spring
WORKDIR /home/spring
RUN mkdir -p ./app/resources
RUN chown spring ./app/resources

USER spring:spring

ARG EXTRACT_DEPENDENCY_PATH=/proj/build/dependency

COPY --from=jvm ${EXTRACT_DEPENDENCY_PATH}/BOOT-INF/lib ./app/lib
COPY --from=jvm ${EXTRACT_DEPENDENCY_PATH}/META-INF ./app/META-INF
COPY --from=jvm ${EXTRACT_DEPENDENCY_PATH}/BOOT-INF/classes ./app

ENTRYPOINT ["java", "-cp", "app:app/lib/*", "org.ionproject.core.CoreApplicationKt"]
