FROM node:16-alpine3.11 AS node

WORKDIR ./core-react
COPY ./core-react/package.json package.json
COPY ./core-react/yarn.lock yarn.lock

RUN yarn install

COPY ./core-react .
COPY ./jvm ../jvm

RUN yarn build

WORKDIR ..

FROM adoptopenjdk/openjdk11:alpine AS jvm

RUN apk add postgresql-client

COPY --from=node ./jvm ./proj
WORKDIR ./proj
RUN mv ./src/test/resources/bin/poll_db_and_build .

ENTRYPOINT [ "./poll_db_and_build" ]
