version: '3'
services:
    db:
      image: postgres:13-alpine
      container_name: core-db-container
      ports:
        - 10021:5432
      environment:
        - POSTGRES_USER=bob
        - POSTGRES_PASSWORD=changeit
        - POSTGRES_DB=core
