version: '3'
# WARNING!
# In order for this procedure to work, you need to run docker-compose
# from the root of the project, such that PWD=<root of the repo folder>
# e.g. cd <root of project> && docker-compose -f .docker/compose_deploy.yaml run --rm core-deploy
#
# Credentials. Create a file named `env_flyway` in this folder, with the contents:
# GITHUB_ACTOR
# GITHUB_TOKEN

services:
    build-flyway:
      build:
        context: ..
        dockerfile: ./project/res/dockerfile_build_flyway
      env_file: ./env_flyway
      container_name: build-flyway-container
      working_dir: "${PWD}"
      network_mode: host
      volumes:
        - "${PWD}:${PWD}"
        - "/var/run/docker.sock:/var/run/docker.sock"