version: '3'
services:
    core:
      build:
        context: ./src
        dockerfile: ./res/dockerfile_ci
      container_name: core-ci-container
      depends_on: [ db ]
      command: [ "run" ]
      ports:
        - 10023:8080
      environment:
        - JDBC_DATABASE_URL=jdbc:postgresql://db:5432/core?user=bob&password=changeit
        - ION_CORE_SECRET_KEY=t8abumA3JBJrd7q0LuN3nSzKGBfslOYb
        - ION_CORE_BASE_URL="localhost:10023"
    db:
      build:
        context: ./src/res
        dockerfile: ./dockerfile_db
      container_name: core-ci-database
      ports:
        - 10021:5432
      environment:
        - POSTGRES_USER=bob
        - POSTGRES_PASSWORD=changeit
        - POSTGRES_DB=core
        - POSTGRES_PORT=10021
