version: '3'
services:
    core:
      build:
        context: ./src
        dockerfile: ./res/dockerfile_ci
      container_name: core-container
      depends_on: [ db ]
      # The entrypoint script will run the server if Argument 1 = "run"
      command: [ "run" ]
      ports:
        - 10023:8080
      environment:
        - JDBC_DATABASE_URL=jdbc:postgresql://db:5432/core?user=bob&password=changeit
    db:
      build:
        context: ./src
        dockerfile: ./res/dockerfile_db
      container_name: pg-container
      ports:
        - 10021:5432
      environment:
        - POSTGRES_USER=bob
        - POSTGRES_PASSWORD=changeit
        - POSTGRES_DB=core
