version: '3'
# WARNING!
# In order for this procedure to work, you need to run docker-compose
# from the root of the project, such that PWD=<root of the repo folder>
# e.g. cd <root of project> && docker-compose -f .docker/compose_deploy.yaml run --rm core-deploy
#
# Credentials. Create a file named `env_deploy` in this folder, with the contents:
# DOCKER_USERNAME
# DOCKER_PASSWORD

services:
    core-deploy:
      build:
        context: ..
        dockerfile: ./project/res/dockerfile_deploy
      env_file: ./env_deploy
      container_name: core-deploy-container