version: '3'
services:
    core-deploy:
      build:
        context: ..
        dockerfile: .docker/dockerfiles/dockerfile_deploy
      container_name: core-deploy-container
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
