version: '3'
services:
    db:
      build:
        context: ./src/res
        dockerfile: ./dockerfile_db
      container_name: core-ci-flyway
      network_mode: host
      environment:
        - POSTGRES_USER=bob
        - POSTGRES_PASSWORD=changeit
        - POSTGRES_DB=core
        - POSTGRES_PORT=10021
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
