#!/bin/sh

set -e

nargs=6
if [ "$#" -ne "$nargs" ]; then
  printf "%s arguments are required:\n\t./%s <hash> <is_valid> <issued_at> <expires_at> <scope> <client_id>\n" \
    "$nargs" "$(basename "$0")"
  exit 1
fi

if [ -z "$CORE_DB_HOST" ] || [ -z "$CORE_DB_USER" ] || [ -z "$CORE_DB_NAME" ] || [ -z "$CORE_DB_PORT" ]; then
  printf "Missing environment variables for DB connectivity:\n\tCORE_DB_HOST, CORE_DB_USER, CORE_DB_NAME or CORE_DB_PORT\n"
  exit 1
fi

psql -w -1 \
  -h "$CORE_DB_HOST" \
  -U "$CORE_DB_USER" \
  -d "$CORE_DB_NAME" \
  -p "$CORE_DB_PORT" \
  -c "INSERT INTO dbo.Token(hash,isValid,issuedAt,expiresAt,claims) VALUES ('$1','$2',$3,$4,'{\"scope\":\"$5\", \"client_id\": $6}')"

