name: Continuous Integration

on:
  push:
    branches-ignore:
      - release/*

jobs:
  build:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and test
        run: docker-compose -f .docker/compose_ci.yaml --build --abort-on-container-exit
