name: Deploy Core on Google Compute Engine

on:
  push:
    branches:
      - release/*

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJ_ID }}
  GCP_INSTANCE: core-instance
  GCP_INSTANCE_ZONE: europe-west2-c
  GCP_REPO: eu.gcr.io
  IMAGE_NAME: core-release-img

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start DB and run tests
        env:
          JDBC_DATABASE_URL: ${{ secrets.LOCAL_JDBC_DATABASE_URL }}
        working-directory: project
        run: ./gradlew pgSetupDb test

      - uses: actions/upload-artifact@v2
        with:
          name: reports-test
          path: project/build/reports/tests/test/
        if: always()

      - name: Stop DB
        working-directory: project
        run: ./gradlew pgStop

  deploy:
    name: Deploy to GCE
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: checkout
        uses: actions/checkout@v2

      # GCloud steps:
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '286.0.0'
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_KEY }}

      - name: gcloud set up
        run: gcloud config set project $GCP_PROJECT_ID

      - name: Configure docker auth
        run: gcloud auth configure-docker

      # Docker steps:
      - name: Rebuild docker image
        working-directory: ./project
        run: docker build -t $IMAGE_NAME .

      - name: Tag image
        run: |
          docker tag $IMAGE_NAME $GCP_REPO/$GCP_PROJECT_ID/$IMAGE_NAME:gh-$GITHUB_SHA &&\
            docker tag $IMAGE_NAME $GCP_REPO/$GCP_PROJECT_ID/$IMAGE_NAME:latest

      - name: Push image
        run: docker push $GCP_REPO/$GCP_PROJECT_ID/$IMAGE_NAME

      # Issue commands to the GCE instances
      - name: Deploy
        run: |-
          gcloud compute instances update-container "$GCP_INSTANCE" \
            --zone "$GCP_INSTANCE_ZONE" \
            --container-image "$GCP_REPO/$GCP_PROJECT_ID/$IMAGE_NAME:gh-$GITHUB_SHA"
