name: Continuous Deployment

on:
  push:
    branches-ignore:
      - release/*

jobs:
  build:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and test
        run: docker-compose -f .docker/compose_ci.yaml run --rm core
  deploy:
    name: Deploy to GCE
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set env file for Docker Compose
        env:
          ENV_FILE_CONTENTS: ${{ secrets.DEPLOY_ENV }}
        run: echo "$ENV_FILE_CONTENTS" > .docker/env_deploy

      # Docker steps:
      - name: Docker Compose run deploy
        run: docker-compose -f .docker/compose_deploy.yaml run --rm core-deploy
